name: Replace firardfortressdev with firardfortress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  replace-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace all instances of firardfortressdev
      run: |
        find . -type f -exec sed -i 's/firardfortressdev/firardfortress/g' {} +

    - name: Configure Git for pushing
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Replace firardfortressdev with firardfortress"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
