name: Replace Text in Files

on: [push]

jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace 'firardfortressdev' with 'firardfortress'
        run: |
          find . -type f \( -name "*.js" -o -name "*.json" -o -name "*.hbs" -o -name "*.css" \) -exec sed -i 's/firardfortressdev/firardfortress/g' {} +

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git commit -m "Replace firardfortressdev with firardfortress" || echo "No changes to commit"
          git push
